
import { Table, TableCell, TableContainer, TableHeader, TableRow } from './styled';

export const TableBarrasRedondas = () => {
  return (
    <TableContainer>
      <Table>
        <thead>
          <tr>
            <TableHeader colSpan={5}>BARRAS REDONDAS</TableHeader>
          </tr>
          <tr>
            <TableHeader>DIÂMETRO Ø</TableHeader>
            <TableHeader>POLEGADA</TableHeader>
            <TableHeader>mm</TableHeader>
            <TableHeader>PESO kg/m</TableHeader>
            <TableHeader>TAMANHO PADRÃO</TableHeader>
          </tr>
        </thead>
        <tbody>
          <TableRow>
            <TableCell>3/16"</TableCell>
            <TableCell>4.76</TableCell>
            <TableCell>0.13</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>1/4"</TableCell>
            <TableCell>6.35</TableCell>
            <TableCell>0.24</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>5/16"</TableCell>
            <TableCell>7.94</TableCell>
            <TableCell>0.39</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>3/8"</TableCell>
            <TableCell>9.53</TableCell>
            <TableCell>0.55</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>7/16"</TableCell>
            <TableCell>11.11</TableCell>
            <TableCell>0.79</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>1/2"</TableCell>
            <TableCell>12.70</TableCell>
            <TableCell>0.99</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>9/16"</TableCell>
            <TableCell>14.29</TableCell>
            <TableCell>1.25</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>5/8"</TableCell>
            <TableCell>15.87</TableCell>
            <TableCell>1.55</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>11/16"</TableCell>
            <TableCell>17.46</TableCell>
            <TableCell>1.90</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>3/4"</TableCell>
            <TableCell>19.05</TableCell>
            <TableCell>2.22</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>13/16"</TableCell>
            <TableCell>20.64</TableCell>
            <TableCell>2.57</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>7/8"</TableCell>
            <TableCell>22.22</TableCell>
            <TableCell>2.96</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>15/16"</TableCell>
            <TableCell>23.81</TableCell>
            <TableCell>3.38</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>1"</TableCell>
            <TableCell>25.40</TableCell>
            <TableCell>3.85</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>1.1/8"</TableCell>
            <TableCell>28.58</TableCell>
            <TableCell>4.79</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>1.1/4"</TableCell>
            <TableCell>31.75</TableCell>
            <TableCell>6.06</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>1.3/8"</TableCell>
            <TableCell>34.92</TableCell>
            <TableCell>7.45</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>1.1/2"</TableCell>
            <TableCell>38.10</TableCell>
            <TableCell>8.94</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>1.3/4"</TableCell>
            <TableCell>44.45</TableCell>
            <TableCell>12.17</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>2"</TableCell>
            <TableCell>50.80</TableCell>
            <TableCell>15.90</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
        </tbody>
      </Table>
    </TableContainer>
  );
};
