import { Table, TableCell, TableContainer, TableHeader, TableRow } from "./styled";

export const TableCantoneiras = () => {
  return (
    <TableContainer>
      <Table>
        <thead>
          <tr>
            <TableHeader colSpan={9}>CANTONEIRAS</TableHeader>
          </tr>
          <tr>
            <TableHeader>ESPESSURA</TableHeader>
            <TableHeader>Pol</TableHeader>
            <TableHeader>mm</TableHeader>
            <TableHeader>1/8"</TableHeader>
            <TableHeader>3/16"</TableHeader>
            <TableHeader>1/4"</TableHeader>
            <TableHeader>5/16"</TableHeader>
            <TableHeader>3/8"</TableHeader>
            <TableHeader>TAMANHO PADRÃO</TableHeader>
          </tr>
        </thead>
        <tbody>
          <TableRow>
            <TableCell>1/2"</TableCell>
            <TableCell>12.70</TableCell>
            <TableCell>0.55</TableCell>
            <TableCell>0.71</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>5/8"</TableCell>
            <TableCell>15.87</TableCell>
            <TableCell>0.71</TableCell>
            <TableCell>0.88</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>3/4"</TableCell>
            <TableCell>19.05</TableCell>
            <TableCell>0.88</TableCell>
            <TableCell>1.04</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>1"</TableCell>
            <TableCell>25.40</TableCell>
            <TableCell>1.20</TableCell>
            <TableCell>1.50</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>1.1/4"</TableCell>
            <TableCell>31.75</TableCell>
            <TableCell>1.62</TableCell>
            <TableCell>2.28</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>1.1/2"</TableCell>
            <TableCell>38.10</TableCell>
            <TableCell>2.46</TableCell>
            <TableCell>3.30</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>2"</TableCell>
            <TableCell>50.80</TableCell>
            <TableCell>4.46</TableCell>
            <TableCell>5.05</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>2.1/2"</TableCell>
            <TableCell>63.50</TableCell>
            <TableCell>6.45</TableCell>
            <TableCell>7.30</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>3"</TableCell>
            <TableCell>76.20</TableCell>
            <TableCell>9.85</TableCell>
            <TableCell>12.37</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>4"</TableCell>
            <TableCell>101.6</TableCell>
            <TableCell>15.39</TableCell>
            <TableCell>22.90</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>6"</TableCell>
            <TableCell>152.4</TableCell>
            <TableCell>31.03</TableCell>
            <TableCell>38.30</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>8"</TableCell>
            <TableCell>203.2</TableCell>
            <TableCell>48.70</TableCell>
            <TableCell>67.00</TableCell>
            <TableCell>6m</TableCell>
          </TableRow>
        </tbody>
      </Table>
    </TableContainer>
  );
};
