name: Deploy via ftp

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # Checkout do repositório

    - name: Setup Node.js 20
      uses: actions/setup-node@v3  # Configura a versão do Node.js
      with:
        node-version: '20'

    - name: Install Dependencies
      run: yarn install  # Instala dependências usando Yarn

    - name: Build Project
      run: yarn build  # Build do projeto

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localDir: "build"
        remoteDir: "/home/gaspartransporte1/"
