name: Deploy via FTP

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install # ou npm install

      - name: Build project
        run: yarn build # ou npm run build

      - name: Check if dist exists
        run: |
          if [ -d "dist" ]; then
            echo "dist directory exists."
          else
            echo "dist directory does not exist."
            exit 1 # Isso interrompe o workflow se o diretório não existir
          fi

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }} 
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "dist"
